---
name: Build
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  SOLUTION: src\CcgVault.sln

jobs:
  build:
    name: build
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Restore Packages
        run: nuget restore ${{ env.SOLUTION }}

      - name: Build Solution
        run: msbuild.exe ${{ env.SOLUTION }} /p:platform="Any CPU" /p:configuration="Release"
