---
name: Build & Test
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    uses: ./.github/workflows/_build.yml
    with:
      version: 98.76.54

  test:
    name: test ${{ needs.build.outputs.version }}
    needs: [build]
    uses: ./.github/workflows/_test.yml
    with:
      artifact-bin: ${{ needs.build.outputs.artifact-bin }}
      artifact-msi: ${{ needs.build.outputs.artifact-msi }}
